version: "3.5"

services:
  larva-cms_build:
    build: ../
    container_name: "larva-cms_build"
    volumes:
      - dist:/usr/src/app/dist

  larva-cms_web:
    image: nginx
    ports:
      - 80:80
    container_name: "larva-cms_web"
    restart: unless-stopped
    volumes:
      - dist:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf

volumes:
  dist:
